alunosJSF/src/main/java/br/com/alunosJSF/PessoaMB.java
package br.com.alunosJSF;

/*
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;
import java.security.Principal;
import java.util.Locale;
import java.util.Map;
import java.util.Collection;
import java.util.Enumeration;
import javax.servlet.AsyncContext;
import javax.servlet.DispatcherType;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.ServletInputStream;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpSession;
import javax.servlet.http.HttpUpgradeHandler;
import javax.servlet.http.Part;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.xml.sax.InputSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperReport;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
*/
import java.io.Serializable;
import java.util.List;
import java.util.ArrayList;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.html.HtmlCommandButton;
import javax.faces.context.FacesContext;
import javax.inject.Named;

@Named
@SessionScoped
public class PessoaMB implements Serializable {
	private String pagina = "login.xhtml";
	private String pdf = "blank.xhtml";
	private String icone = new String();
	private Login login = new Login();
	private boolean logado = false;
	private Pessoa pessoa = new Pessoa();
	private Validador validador = new Validador();
	private static String id = "AAA000";
	private List<Pessoa> pessoas = new ArrayList<Pessoa>();
	private HtmlCommandButton cmdBtnLogin;
	private HtmlCommandButton cmdBtnEntrarLayout;
	private HtmlCommandButton cmdBtnCadastro;
	private HtmlCommandButton cmdBtnEntrarCadastro;
	private HtmlCommandButton cmdBtnEditar;
	private HtmlCommandButton cmdBtnLog;
	private HtmlCommandButton cmdBtnEntrarPdf;
	
	@EJB
	private PessoaEJB pessoaEJB;
	
	public PessoaMB() {
		
	}
	
	public PessoaMB(Pessoa pessoa) {
		this.pessoa = pessoa;
	}
	
	@PostConstruct
	void init() {
		try {
			List<PessoaJPA> pessoasJPA = pessoaEJB.getListPessoaJPA();
			
			for (PessoaJPA p : pessoasJPA) {
				pessoa.setIdBanco(p.getIdBanco());
				pessoa.setId(generateId());
				pessoa.setNome(p.getNome());
				
				String cpf = generateCPF();
				cpf = cpf.substring(0, 3).concat(".").concat(cpf.substring(3, 6)).concat(".").concat(cpf.substring(6, 9)).concat("-").concat(cpf.substring(9, 11));
				
				pessoa.setCpf(cpf);
				pessoa.setEmail(id.concat("@email.com"));
				pessoa.setDataNascimento("03/12/1998");
				pessoa.setTelefone("(16) 3964-3577");
				pessoa.setTelefone2("(16) 98850-5989");
				pessoa.setEstado("São Paulo");
				pessoa.setCidade("Ribeirão Preto");
				pessoa.setRua("Rua 1");
				pessoa.setNumero("1");
				pessoa.setCep("12345-678");
				pessoa.setBairro("Bairro 1");
				
				pessoas.add(pessoa.copy());
				pessoa = new Pessoa();
			}
		} catch(Exception e) {
			validador.mostraMensagemERROR("NÃO FOI POSSÍVEL REALIZAR A QUERY NO BANCO DE DADOS", "Contact admin.");
		}
	}
	
	public String getIcone() {
		icone = (pagina.equals("layout.xhtml")) ? "img/icone_chapeuzinho.png" : (pagina.equals("login.xhtml") ? "img/icone_login.png" : (pagina.equals("cadastro.xhtml") ? "img/icone_cadastro.png" : (pagina.equals("editar.xhtml") ? "img/icone_editar.png" : "img/icone_chapeuzinho.png")));
		
		return icone;
	}
	
	public void initPessoa() {
		pessoa = new Pessoa();
	}
	
	public void initEdicao(String id) {
		pessoa = getIndexOfPessoas(pessoas, id).copy();
	}
	
	public void initExclusao(String id) {
		pessoa = getIndexOfPessoas(pessoas, id).copy();
	}
	
	private static String calcDigVerif(String num) {
		Integer primDig, segDig;
		int soma = 0, peso = 10;
		for (int i = 0; i < num.length(); i++)
		soma += Integer.parseInt(num.substring(i, i + 1)) * peso--;
		
		if (soma % 11 == 0 | soma % 11 == 1)
	        primDig = new Integer(0);
	    else
	        primDig = new Integer(11 - (soma % 11));
		
	    soma = 0;
	    peso = 11;
	    for (int i = 0; i < num.length(); i++)
	            soma += Integer.parseInt(num.substring(i, i + 1)) * peso--;
	    
	    soma += primDig.intValue() * 2;
	    if (soma % 11 == 0 | soma % 11 == 1)
	        segDig = new Integer(0);
	    else
	        segDig = new Integer(11 - (soma % 11));
	    
	    return primDig.toString() + segDig.toString();
	}
	
	private String generateCPF() {
		String iniciais = "";
	    Integer numero;
	    for (int i = 0; i < 9; i++) {
	        numero = new Integer((int) (Math.random() * 10));
	        iniciais += numero.toString();
	    }
	    return iniciais + calcDigVerif(iniciais);
	}
	
	public String getIconLogin() {
		return logado == true ? "ui-icon-unlocked" : "ui-icon-locked";
	}
	
	public void entrarLogin() {
		pagina = "login.xhtml";
	}
	
	public void entrarLayout() {
		pdf = "blank.xhtml";
		pagina = "layout.xhtml";
	}
	
	public void entrarCadastro() {
		initPessoa();
		pagina = "cadastro.xhtml";
	}
	
	public void entrarEditar(String id) {
		initEdicao(id);
		pagina = "editar.xhtml";
	}
	
	public void entrarExcluir(String id) {
		initExclusao(id);
		pagina = "excluir.xhtml";
	}
	
	public void entrarPdf() {
		pagina = "gerarPdf.xhtml";
	}
	
	public String getPagina() {
		return pagina;
	}
	
	public void setPagina(String pagina) {
		this.pagina = pagina;
	}
	
	public String getWelcome() {
		return login.getWelcome();
	}
	
	public String getUsuario() {
		return login.getUsuario() == null ? "" : login.getUsuario();
	}
	
	public void setUsuario(String usuario) {
		login.setUsuario(usuario.toLowerCase().trim());
	}
	
	public String getSenha() {
		return login.getSenha() == null ? "" : login.getSenha();
	}
	
	public void setSenha(String senha) {
		login.setSenha(senha);
	}
	
	public String getConfirmaSenha() {
		return login.getConfirmaSenha() == null ? "" : login.getConfirmaSenha();
	}
	
	public void setConfirmaSenha(String confirmaSenha) {
		login.setConfirmaSenha(confirmaSenha);
	}
	
	public Login getLogin() {
		return login;
	}
	
	public String loginMB() {
		if (login.login().equals("#")) {
			entrarLogin(); 
		} else{
			entrarLayout();
		}
		return (pagina.equals("layout")) ? "index" : null;
	}
	
	private String generateId() {
		int idNumber = Integer.parseInt(id.substring(3, id.length()));
		id = id.substring(0, 3).concat(padString(Integer.toString(idNumber+1), '0', 3));
		
		if (idNumber > 999) {
			char[] charLetters = id.substring(0, 3).toCharArray();
			
			if (charLetters[2] == 'Z') {
				charLetters[2] = 'A';
				
				if (charLetters[1] == 'Z') {
					charLetters[1] = 'A';
					charLetters[0] += 1;
				} else {
					charLetters[1] += 1;
				}
			} else {
				charLetters[2] += 1;
			}
			
			idNumber = 0;

			StringBuilder strBuildLetterId = new StringBuilder();
			for (char content : charLetters) {
				strBuildLetterId.append(content);
			}
			id = strBuildLetterId.toString().concat("001");
		}
		
		return id.substring(0, 3).concat(padString(Integer.toString(idNumber), '0', 3));
	}
	
	public Pessoa getPessoa() {
		return pessoa;
	}
	
	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}
	
	public String getId() {
		return pessoa.getId();
	}
	
	public void setId(String id) {
		pessoa.setId(id);
	}
	
	public String getNome() {
		return pessoa.getNome();
	}
	
	public void setNome(String nome) {
		String[] nomeSplit = nome.trim().toUpperCase().split(" ");
		StringBuilder strBuildNome = new StringBuilder();
		
		for (String content : nomeSplit) {
			if (!content.equals(" ") && !content.equals("")) {
				strBuildNome.append(content + " ");
			}
		}
		this.pessoa.setNome(strBuildNome.toString().trim());
	}
	
	public String getEmail() {
		return pessoa.getEmail();
	}
	
	public void setEmail(String email) {
		this.pessoa.setEmail(email.trim().toLowerCase());
	}
	
	public String getCpf() {
		return pessoa.getCpf();
	}
	
	public void setCpf(String cpf) {
		this.pessoa.setCpf(cpf.trim());
	}
	
	public String getDataNascimento() {
		return pessoa.getDataNascimento();
	}
	
	public void setDataNascimento(String dataNascimento) {
		this.pessoa.setDataNascimento(dataNascimento.trim());
	}
	
	public String getTelefone() {
		return pessoa.getTelefone();
	}
	
	public void setTelefone(String telefone) {
		this.pessoa.setTelefone(telefone.trim());
	}
	
	public String getTelefone2() {
		return pessoa.getTelefone2();
	}
	
	public void setTelefone2(String telefone2) {
		this.pessoa.setTelefone2(telefone2.trim());
	}
	
	public String getRua() {
		return pessoa.getRua();
	}
	
	public void setRua(String rua) {
		String[] ruaSplit = rua.trim().toLowerCase().split(" ");
		StringBuilder strBuildRua = new StringBuilder();
		
		for (String content : ruaSplit) {
			if (!content.equals(" ") && !content.equals("")) {
				strBuildRua.append(content + " ");
			}
		}
		this.pessoa.setRua(strBuildRua.toString().trim());
	}
	
	public String getNumero() {
		return pessoa.getNumero();
	}
	
	public void setNumero(String numero) {
		String[] numeroSplit = numero.trim().toUpperCase().split(" ");
		StringBuilder strBuildNumero = new StringBuilder();
		
		for (String content : numeroSplit) {
			if (!content.equals(" ") && !content.equals("")) {
				strBuildNumero.append(content);
			}
		}
		this.pessoa.setNumero(strBuildNumero.toString());
	}
	

alunosJSF/WebContent/blank.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Index</title>
	<link rel="icon" href="#{pessoaMB.icone}"/>
	
	<style>
		body {
			background: url("img/PDFGenerator_wallpaper.png");
			background-size: 100%;
			position: "absolute";
			opacity: 1;
		}
		
		#pagina {
			
		}
	</style>
</h:head>

<h:body>
	<div align="center">
		<h:panelGroup id="blank" layout="block" ></h:panelGroup>
	</div>
</h:body>
</html>

alunosJSF/WebContent/excluir.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Index</title>
	<link rel="icon" href="img/icone_excluir.png"/>
	
	<style>
		:root::after {
			background: url("img/escola_wallpaper_excluir.jpg");
			background-attachment: scroll;
			background-origin: border-box;
			background-repeat: no-repeat;
			background-clip: border-box;
			background-size: 100%;
			content: "";
			opacity: 0.5;
			top: 2px;
			left: 0;
			bottom: 0;
			right: 0;
			position: absolute;
			z-index: -1;
			background-position: 100% 100%;
		}
		
		div:nth-child(2){
			background: url("img/tabView_wallpaper.png");
			opacity: 1;
		}
	</style>
</h:head>

<h:body>
	<div id="tabViewExcluirAluno" align="center">
		<p:tabView>
			<p:tab title="EXCLUIR ALUNO">
				<h:form>
					<p:messages>
						<p:autoUpdate/>
					</p:messages>
					
					<h:panelGrid columns="5" cellpadding="4">
						<p:outputLabel for="excluirNome"
							value="Tem certeza que deseja excluir o aluno" />
						<p:outputLabel id="excluirNome" value="#{pessoaMB.nome}" />
						
						<p:outputLabel for="excluirId" value=", com ID:"/>
						<p:outputLabel id="excluirId" value="#{pessoaMB.id}"/>
						
						<p:outputLabel for="excluirNome" value="?" />
					</h:panelGrid>
					<h:panelGrid columns="2" cellpadding="7">
						<p:commandButton id="cmdBtnExcluir" value="SIM" icon="ui-icon-check"
							action="#{pessoaMB.excluirPessoa}" update="pagina"/>

						<p:commandButton id="cmdBtnNaoExcluir" value="NAO" icon="ui-icon-closethick"
							action="#{pessoaMB.naoRealizarAcao}" update="pagina"/>
					</h:panelGrid>
				</h:form>
			</p:tab>
		</p:tabView>
	</div>
</h:body>
</html>

alunosJSF/WebContent/gerarPdf.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Index</title>
	<link rel="icon" href="#{pessoaMB.icone}"/>
	
	<style>
		#pagina {
			
		}
		
		div:nth-child(2){
			background: url("img/tabView_wallpaper.png");
			opacity: 1;
		}
	</style>
</h:head>

<h:body>
	<div align="center">
		<p:tabView>
			<p:tab title="LISTAGEM DE ALUNOS">
				<h:form>
					<p:commandButton value="GERAR PDF" binding="#{pessoaMB.cmdBtnEntrarPdf}"
						action="#{pessoaMB.entrarPdfView}" icon="ui-icon-document-b" ajax="false"/>
				</h:form>
				
				<br/><br/>
				
				<h:form>
					<p:commandButton value="VOLTAR AO LAYOUT" binding="#{pessoaMB.cmdBtnEntrarLayout}"
						action="#{pessoaMB.entrarLayout}" update="pagina" ajax="false"/>
				</h:form>
			</p:tab>
		</p:tabView>
		
		<br/>
		
		<ui:include src="#{pessoaMB.pdf}"/>
	</div>
</h:body>
</html>

alunosJSF/WebContent/index.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Index</title>
	<link rel="icon" href="#{pessoaMB.icone}"/>
	
	<style>
		#pagina {
			
		}
	</style>
</h:head>

<h:body>
	<div align="center">
		<h:panelGroup id="pagina" layout="block" >
			<p:panel>
				<ui:include src="#{pessoaMB.pagina}"/>
			</p:panel>
		</h:panelGroup>
	</div>
</h:body>
</html>

alunosJSF/WebContent/layout.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Test Layout</title>
	<link rel="icon" href="img/icone_chapeuzinho.png"/>
	
	<style type="text/css">
		.ui-datalist .ui-datalist-content {
			border: 0 none
		}
		
		.ui-datalist ul {
			padding: 0px 10px 0 20px;
			margin: 5px 0;
		}
		
		.value {
			font-weight: bold;
		}
		
		.ui-autocomplete-itemtip {
			-moz-box-sizing: content-box;
			-webkit-box-sizing: content-box;
			box-sizing: content-box;
		}
		
		/*demo*/
		.ui-dataview-list .ui-dataview-row {
			border-bottom: 1px solid #A8A8A8;
			padding: 25px 10px;
			/* with the exported variables from Nova and Luna Themes*/
			border-bottom-color: var(- -input-border-color, #A8A8A8);
		}
		
		.logo {
			width: 5%;
		}
		
		.detail {
			width: 85%;
			padding-left: 25px;
		}
		
		.ui-datatable .ui-datatable-header {
			text-align: right !important;
		}
		
		.ui-button-text-only .ui-button-text {
			padding: 0.3em 0.4em;
		}
		
		.ui-selectcheckboxmenu-panel .ui-selectcheckboxmenu-header .ui-chkbox {
			visibility: hidden;
		}
		
		.ui-filter-column .ui-column-customfilter .custom-filter {
			width: 100%;
			box-sizing: border-box;
		}
		
		.year-spinner input {
			width: 100%;
			box-sizing: border-box;
		}
		
		#tabViewTestLayout::after{
			background: url("img/escola_wallpaper_layout.jpg");
			background-attachment: scroll;
			background-origin: border-box;
			background-repeat: no-repeat;
			background-clip: border-box;
			background-size: 100%;
			content: "";
			opacity: 0.5;
			top: 2px;
			left: 0;
			bottom: 0;
			right: 0;
			position: absolute;
			z-index: -1;
			background-position: 100% 100%;
		}
		
		div:nth-child(2){
			background: url("img/tabView_wallpaper.png");
			opacity: 1;
		}
	</style>
</h:head>

<h:body>
	<div id="tabViewTestLayout" align="center">
		<p:tabView id = "abaLayout">
			<p:tab title="ALUNOS">
				<f:verbatim><hr/></f:verbatim>
				<h:panelGrid columns="2" cellpadding="4">
					<h:form>
						<p:outputLabel value="#{pessoaMB.getWelcome()}"/>
						<p:commandButton class="btnLog" action="#{pessoaMB.realizarLogin()}"
							icon="#{pessoaMB.iconLogin}" binding="#{pessoaMB.cmdBtnLog}"
							value="#{pessoaMB.botaoLog()}" update="pagina" ajax="false"/>
					</h:form>
				</h:panelGrid>
				<f:verbatim><hr/></f:verbatim>
				
				<br/>
				
				<h:form>
					<p:commandButton value="NOVO ALUNO" binding="#{pessoaMB.cmdBtnEntrarCadastro}"
						action="#{pessoaMB.entrarCadastro}" update="pagina" ajax="false" icon="ui-icon-circle-plus"/>
					
					<br/><br/>
					
					<p:commandButton value="GERAR LISTAGEM DOS ALUNOS (PDF)" binding="#{pessoaMB.cmdBtnEntrarPdf}"
						action="#{pessoaMB.entrarPdf()}" icon="ui-icon-document-b" ajax="false"/>
					
					<br/><br/>
				</h:form>
				
				<h:form>
					<p:dataTable var="alunoInfo" rows="5" paginator="true" paginatorAlwaysVisible="false"
					value="#{dtFilterView.viewAlunos}" widgetVar="alunosTable" paginatorPosition="bottom"
					emptyMessage="Nenhum aluno encontrado."
						filteredValue="#{dtFilterView.filteredAlunos}">
						<p:column filterBy="#{alunoInfo.id}" sortable="true" sortBy="#{alunoInfo.id}"
							headerText="Id" filterMatchMode="contains" width="10%">
							<h:outputText value="#{alunoInfo.id}" />
						</p:column>
						
						<p:column filterBy="#{alunoInfo.nome}" sortable="true" sortBy="#{alunoInfo.nome}"
							headerText="Nome" filterMatchMode="contains" >
							<h:outputText value="#{alunoInfo.nome}" />
						</p:column>
						
						<p:column filterBy="#{alunoInfo.email}" sortable="true" headerText="Email"
							sortBy="#{alunoInfo.email}" filterMatchMode="contains" width="20%">
							<h:outputText value="#{alunoInfo.email}" />
						</p:column>
						
						<p:column filterBy="#{alunoInfo.cpf}" sortable="true" sortBy="#{alunoInfo.cpf}"
							headerText="CPF" filterMatchMode="contains" width="20%">
							<h:outputText value="#{alunoInfo.cpf}" />
						</p:column>
						
						<p:column width="10%">
							<p:commandButton id="cmdBtnEditar" value=". Editar_" icon="ui-icon-pencil"
								action="#{pessoaMB.entrarEditar(alunoInfo.id)}" update="pagina" ajax="false"/>
							<!--<p:spacer width="24" />-->
							<f:verbatim><hr/></f:verbatim>
							<p:commandButton id="cmdBtnExcluir" value=". Excluir" icon="ui-icon-trash"
								action="#{pessoaMB.entrarExcluir(alunoInfo.id)}" update="pagina" ajax="false"/>
						</p:column>
					</p:dataTable>
				</h:form>
			</p:tab>
		</p:tabView>
	</div>
</h:body>
</html>

alunosJSF/WebContent/pdfView.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Index</title>
	<link rel="icon" href="#{pessoaMB.icone}"/>
	
	<style>
		#pagina {
			
		}
	</style>
</h:head>

<h:body>
	<div align="center">
		<p:media value="#{pdfControlerView.streamedContent}" player="pdf" width="100%" height="650" cache="false">
		    Seu navegador não suporta a exibição para pdf, <h:outputLink value="#{pdfControlerView.streamedContent}">clique aqui</h:outputLink> para baixá-lo.
		</p:media>
	</div>
</h:body>
</html>

alunosJSF/WebContent/testeIndex.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Frameset//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Index</title>
</h:head>

<h:body>
	<div id="div" align="center">
		<h:form>
			<p:commandButton value="index" action="#{testeSPA.entrarLogin}" update="pagina"/>
			<p:commandButton value="Layout" action="#{testeSPA.entrarLayout}" update="pagina"/>
		</h:form>
		
		<h:panelGroup id="pagina" layout="block">
			<p:panel>
				<ui:include src="#{testeSPA.pagina}"/>
			</p:panel>
		</h:panelGroup>
	</div>
</h:body>
</html>